import type { User, Task, AppSettings } from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 'user_admin',
    username: 'admin',
    email: 'admin@agnus.local',
    name: 'Admin Manager',
    role: 'admin',
    avatar: '',
    is_active: true,
    created: new Date(Date.now() - 86400000 * 30).toISOString(),
    updated: new Date().toISOString(),
  },
  {
    id: 'user_member1',
    username: 'sina',
    email: 'sina@agnus.local',
    name: 'Sina',
    role: 'member',
    avatar: '',
    is_active: true,
    created: new Date(Date.now() - 86400000 * 20).toISOString(),
    updated: new Date().toISOString(),
  },
  {
    id: 'user_member2',
    username: 'ali',
    email: 'ali@agnus.local',
    name: 'Ali',
    role: 'member',
    avatar: '',
    is_active: true,
    created: new Date(Date.now() - 86400000 * 15).toISOString(),
    updated: new Date().toISOString(),
  },
  {
    id: 'user_member3',
    username: 'sara',
    email: 'sara@agnus.local',
    name: 'Sara',
    role: 'member',
    avatar: '',
    is_active: true,
    created: new Date(Date.now() - 86400000 * 10).toISOString(),
    updated: new Date().toISOString(),
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task_1',
    task_id: 'MCR-1001',
    body: 'Analyze dataset for Mercor prompt evaluation and verify logical consistency across responses.',
    assigned_to: 'user_member1',
    status: 'assigned',
    member_verdict: '',
    member_verdict_date: '',
    admin_verdict: '',
    admin_verdict_date: '',
    admin_notes: '',
    payment_status: 'not_applicable',
    payment_amount_usd: 0,
    payment_date: '',
    created: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated: new Date(Date.now() - 86400000 * 3).toISOString(),
    expand: { assigned_to: MOCK_USERS[1] },
  },
  {
    id: 'task_2',
    task_id: 'MCR-1002',
    body: 'Evaluate SWF edge case submission for complex instruction following test suite.',
    assigned_to: 'user_member1',
    status: 'working',
    member_verdict: '',
    member_verdict_date: '',
    admin_verdict: '',
    admin_verdict_date: '',
    admin_notes: 'Under review by member',
    payment_status: 'not_applicable',
    payment_amount_usd: 0,
    payment_date: '',
    created: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated: new Date(Date.now() - 86400000 * 1).toISOString(),
    expand: { assigned_to: MOCK_USERS[1] },
  },
  {
    id: 'task_3',
    task_id: 'MCR-1003',
    body: 'Process SWOF task batch 4 and double check constraint formatting.',
    assigned_to: 'user_member1',
    status: 'swof',
    member_verdict: 'swof',
    member_verdict_date: new Date(Date.now() - 86400000 * 1).toISOString(),
    admin_verdict: '',
    admin_verdict_date: '',
    admin_notes: 'Submitted without failure',
    payment_status: 'not_applicable',
    payment_amount_usd: 0,
    payment_date: '',
    created: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated: new Date(Date.now() - 86400000 * 1).toISOString(),
    expand: { assigned_to: MOCK_USERS[1] },
  },
  {
    id: 'task_4',
    task_id: 'MCR-1004',
    body: 'Review Mercor Studio submission feedback for coding tasks.',
    assigned_to: 'user_member2',
    status: 'approved',
    member_verdict: 'swof',
    member_verdict_date: new Date(Date.now() - 86400000 * 5).toISOString(),
    admin_verdict: 'approved',
    admin_verdict_date: new Date(Date.now() - 86400000 * 2).toISOString(),
    admin_notes: 'Passed Studio validation cleanly.',
    payment_status: 'paid',
    payment_amount_usd: 15,
    payment_date: new Date(Date.now() - 86400000 * 1).toISOString(),
    created: new Date(Date.now() - 86400000 * 6).toISOString(),
    updated: new Date(Date.now() - 86400000 * 1).toISOString(),
    expand: { assigned_to: MOCK_USERS[2] },
  },
  {
    id: 'task_5',
    task_id: 'MCR-1005',
    body: 'Check failure logs for failed API pipeline run.',
    assigned_to: 'user_member3',
    status: 'swf',
    member_verdict: 'swf',
    member_verdict_date: new Date(Date.now() - 86400000 * 1).toISOString(),
    admin_verdict: '',
    admin_verdict_date: '',
    admin_notes: 'Requires admin edit in studio.',
    payment_status: 'not_applicable',
    payment_amount_usd: 0,
    payment_date: '',
    created: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated: new Date(Date.now() - 86400000 * 1).toISOString(),
    expand: { assigned_to: MOCK_USERS[3] },
  },
];

export const MOCK_SETTINGS: AppSettings = {
  id: 'settings_1',
  usd_to_irr_rate: 580000,
  updated: new Date().toISOString(),
};
